name: Automate Versioning and Release

on:
  push:
    branches:
      - main
  pull_request:
    branches:
      - main

jobs:
  release:
    runs-on: ubuntu-latest
    steps:
    
      # Étape 1: Vérifier le code
      - name: Checkout code
        uses: actions/checkout@v2

      # Étape 2: Installer Node.js
      - name: Set up Node.js
        uses: actions/setup-node@v2
        with:
          node-version: '16'

      # Étape 3: Installer les dépendances
      - name: Install dependencies
        run: |
          npm ci

      # Étape 4: Lancer les tests
      - name: Run tests
        run: |
          npm test

      # Étape 5: Lancer le script de release
      - name: Run release script
        run: |
          ./release.sh

      # Étape 6: Push les changements si release a eu lieu
      - name: Push changes
        run: |
          git config --global user.name "GitHub Actions"
          git config --global user.email "actions@github.com"
          git push --follow-tags
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
